# Generated by Django 4.1.7 on 2023-05-08 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_specialist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="specialist",
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disease",
                    models.CharField(
                        choices=[
                            ("Acne", "Acne"),
                            ("Impetigo", "Impetigo"),
                            ("Arthritis", "Arthritis"),
                            ("Pneumonia", "Pneumonia"),
                            ("Heart Attack,Allergy", "Heart Attack,Allergy"),
                            ("Hyperthyroidism", "Hyperthyroidism"),
                            ("Common Cold", "Common Cold"),
                            ("Typhoid", "Typhoid"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "specializations",
            },
        ),
    ]
