# Generated by Django 4.1.7 on 2023-05-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_user_specialist_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialization",
            name="disease",
            field=models.CharField(
                choices=[
                    ("Acne", "Acne"),
                    ("Impetigo", "Impetigo"),
                    ("Arthritis", "Arthritis"),
                    ("Pneumonia", "Pneumonia"),
                    ("Heart Attack,Allergy", "Heart Attack,Allergy"),
                    ("Hyperthyroidism", "Hyperthyroidism"),
                    ("Common Cold", "Common Cold"),
                    ("Typhoid", "Typhoid"),
                    ("Fungal Infection", "Fungal Infection"),
                ],
                max_length=100,
            ),
        ),
    ]
