# Generated by Django 4.1.7 on 2023-05-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
